source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rake'

group :test, :development do
  gem 'pry'
  <%- if options.rspec? -%>
  gem 'capybara'
  gem 'rspec'
  gem 'launchy'
  <%- end -%>
end

